MEDISMART/Models/ErrorViewModel.cs
namespace MEDISMART.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MEDISMART/Models/LoginModel.cs
using System.ComponentModel.DataAnnotations;

namespace MEDISMART.Models
{
    public class LoginModel
    {
        [Required(ErrorMessage = "Campo requerido")]
        public string? Usuario { get; set; }
        [Required(ErrorMessage = "Campo requerido")]
        public string? Clave { get; set; }
    }
}

MEDISMART/Models/UsuarioModel.cs
using System.ComponentModel.DataAnnotations;

namespace MEDISMART.Models
{
    public class UsuarioModel
    {
        [Key]
        public int Id_Usuario { get; set; }
        [Required(ErrorMessage = "Campo requerido")]
        public string? Nombre { get; set; }
        [Required(ErrorMessage = "Campo requerido")]

        public string? Direccion { get; set; }
        [Required(ErrorMessage = "Campo requerido")]

        public int Edad { get; set; }
        [Required(ErrorMessage = "Campo requerido")]

        public string? Usuario { get; set; }
        [Required(ErrorMessage = "Campo requerido")]
        public string? Clave { get; set; }
    }
}

MEDISMART/Controllers/CuentaController.cs
using MEDISMART.Data;
using MEDISMART.Models;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Data.SqlClient;

namespace MVC.Controllers
{
    public class CuentaController : Controller
    {
        private readonly DbContext _contexto;

        public CuentaController(DbContext contexto)
        {
            _contexto = contexto;
        }

        public ActionResult Registrar()
        {
            return View("Registrar");
        }

        [HttpPost]
        public ActionResult Registrar(UsuarioModel u)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (SqlConnection con = new(_contexto.Valor))
                    {
                        using (SqlCommand cmd = new("sp_registrar", con))
                        {
                            cmd.CommandType = CommandType.StoredProcedure;
                            cmd.Parameters.Add("@Nombre", SqlDbType.VarChar).Value = u.Nombre;
                            cmd.Parameters.Add("@Direccion", SqlDbType.VarChar).Value = u.Direccion;
                            cmd.Parameters.Add("@Edad", SqlDbType.Int).Value = u.Edad;
                            cmd.Parameters.Add("@Usuario", SqlDbType.VarChar).Value = u.Usuario;
                            cmd.Parameters.Add("@Clave", SqlDbType.VarChar).Value = u.Clave;
                            con.Open();
                            cmd.ExecuteNonQuery();
                            con.Close();
                        }
                    }
                    return RedirectToAction("Index", "Home");
                }
            }
            catch (Exception)
            {
                return View("Registrar");
            }
            ViewData["error"] = "Error de credenciales";
            return View("Registrar");
        }


        public ActionResult Login()
        {
            return View("Login");
        }

        [HttpPost]
        public ActionResult Login(LoginModel login)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (SqlConnection con = new(_contexto.Valor))
                    {
                        using (SqlCommand cmd = new("sp_login", con))
                        {
                            cmd.CommandType = CommandType.StoredProcedure;
                            cmd.Parameters.Add("@Usuario", SqlDbType.VarChar).Value = login.Usuario;
                            cmd.Parameters.Add("@Clave", SqlDbType.VarChar).Value = login.Clave;
                            con.Open();

                            SqlDataReader dr = cmd.ExecuteReader();

                            if (dr.Read())
                            {
                                Response.Cookies.Append("user", "Bienvenido " + login.Usuario);
                                return RedirectToAction("Index", "Home");
                            }
                            else
                            {
                                ViewData["error"] = "Error de credenciales";
                            }

                            con.Close();
                        }
                    }
                    return RedirectToAction("Index", "Home");
                }
            }
            catch (Exception)
            {
                return View("Login");
            }
            return View("Login");
        }

        public ActionResult Logout()
        {
            Response.Cookies.Delete("user");
            return RedirectToAction("Index", "Home");
        }

        /*
        //COMPRABACIÓN PARA USUARIOS DUPLICADOS
        private void addNewAppName(string Nombre)
        {
            using (SqlConnection cnx = new SqlConnection(ConfigurationManager.ConnectionStrings["cn"].ToString()))
            {
                SqlCommand cmd = new SqlCommand("sp_registrar", cnx);

                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.Add("@Nombre", SqlDbType.VarChar, 50).Value = Nombre;
                try
                {
                    cnx.Open();
                    if (cmd.ExecuteNonQuery() != 1)
                    {
                        MessageBox.Show("El nombre ya está registrado!", "Error:", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    }
                    else
                    {
                        MessageBox.Show("El guardado ah sido existoso!!!!", "Agregación exitosa!!!!", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
                    }
                }
                catch
                {
                    MessageBox.Show("Ha habido un error, intenta de nuevo.", "Connection error:", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
                finally
                {
                    if (cnx.State == ConnectionState.Open) { cnx.Close(); }
                }
            }
        }
        */
    }
}

MEDISMART/Controllers/HomeController.cs
using MEDISMART.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace MEDISMART.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            ViewData["usuario"] = Request.Cookies["user"];
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MEDISMART/Views/Cuenta/Login.cshtml
@model LoginModel
@{
    ViewData["Title"] = "Login";
}

<form method="post">
<div class="container register">
    <div class="row">
        <div class="col-md-3 register-left"></div>
        <div class="col-md-9 register-right">
            <div class="tab-content">
                <div class="col-md-6">
                    <div class="form-group">
                        <span asp-validation-for="Usuario" class="text-danger"></span>
                        <input asp-for="Usuario" class="form-control" placeholder="Usuario" type="text"/>
                    </div>
                    <br/>
                    <div class="form-group">
                        <span asp-validation-for="Clave" class="text-danger"></span>
                        <input asp-for="Clave" class="form-control" placeholder="Password" type="Password"/>
                    </div>
                </div>
                <div class="col-md-6">
                    <input type="submit" value="Log in" class="btn btn-primary" asp-action="Login" asp-controller="Cuenta"/>
                </div>
            </div>
        </div>
    </div>
</div>
</form>

MEDISMART/Views/Cuenta/Registrar.cshtml
@model UsuarioModel
@{
    ViewData["Title"] = "Registrarse";
}

<<form method="post">
    <div class="container register">
        <div class="row">
            <div class="col-md-3 register-left"></div>
            <div class="col-md-9 register-right">
                <div class="tab-content">
                    <div class="col-md-6">
                        <div class="form-group">
                            <span asp-validation-for="Nombre" class="text-danger"></span>
                            <input asp-for="Nombre" class="form-control" placeholder="Nombre" type="text" />
                        </div>
                        <br />
                        <div class="form-group">
                            <span asp-validation-for="Direccion" class="text-danger"></span>
                            <input asp-for="Direccion" class="form-control" placeholder="Direcccion" type="text" />
                        </div>
                        <br />
                        <div class="form-group">
                            <span asp-validation-for="Edad" class="text-danger"></span>
                            <input asp-for="Edad" class="form-control" placeholder="Edad" type="text" />
                        </div>
                        <br />
                        <div class="form-group">
                            <span asp-validation-for="Usuario" class="text-danger"></span>
                            <input asp-for="Usuario" class="form-control" placeholder="Usuario" type="text" />
                        </div>
                        <br />
                        <div class="form-group">
                            <span asp-validation-for="Clave" class="text-danger"></span>
                            <input asp-for="Clave" class="form-control" placeholder="Password" type="Password" />
                        </div>
                    </div>
                    <div class="col-md-6">
                        <input type="submit" value="Registrarse" class="btn btn-primary" asp-action="Registrar" asp-controller="Cuenta" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

MEDISMART/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">@ViewData["usuario"]</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MEDISMART/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MEDISMART</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MEDISMART.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MEDISMART</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cuenta" asp-action="Registrar">Registrarse</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cuenta" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cuenta" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MEDISMART - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>